# Generated by Django 5.2.3 on 2025-06-15 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, unique=True, verbose_name='Город')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО полностью')),
                ('position', models.CharField(choices=[('Менеджер', 'Менеджер'), ('Senior-разработчик', 'Senior-разработчик'), ('Middle-разработчик', 'Middle-разработчик'), ('Junior-разработчик', 'Junior-разработчик')], max_length=30, verbose_name='Должность')),
                ('specialization', models.CharField(choices=[('Python', 'Python'), ('DevOps', 'DevOps')], max_length=30, verbose_name='Специализация')),
                ('telegram_nick', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ник в Telegram')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='Руководитель')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.location', verbose_name='Рабочее место')),
            ],
        ),
    ]
