# Generated by Django 5.2.3 on 2025-06-15 08:15

from django.db import migrations


def add_locations(apps, schema_editor):
    Location = apps.get_model("employees", "Location")

    Location.objects.bulk_create([
        Location(city="Москва", country="Россия"),
        Location(city="Санкт-Петербург", country="Россия"),
        Location(city="Париж", country="Франция"),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_locations),
    ]
